//
//  File.swift
//  
//
//  Created by Maxime De Greve on 22/07/2021.
//

import Vapor

enum Gender: String, Codable {
    case Agender = "Agender"
    case Androgyne = "Androgyne"
    case Androgynous = "Androgynous"
    case Bigender = "Bigender"
    case Cis = "Cis"
    case Cisgender = "Cisgender"
    case CisFemale = "Cis Female"
    case CisMale = "Cis Male"
    case CisMan = "Cis Man"
    case CisWoman = "Cis Woman"
    case CisgenderFemale = "Cisgender Female"
    case CisgenderMale = "Cisgender Male"
    case CisgenderMan = "Cisgender Man"
    case CisgenderWoman = "Cisgender Woman"
    case FemaletoMale = "Female to Male"
    case Female = "Female"
    case FTM = "FTM"
    case GenderFluid = "Gender Fluid"
    case GenderNonconforming = "Gender Nonconforming"
    case GenderQuestioning = "Gender Questioning"
    case GenderVariant = "Gender Variant"
    case Genderqueer = "Genderqueer"
    case Intersex = "Intersex"
    case MaletoFemale = "Male to Female"
    case Male = "Male"
    case MTF = "MTF"
    case Neither = "Neither"
    case Neutrois = "Neutrois"
    case NonBinary = "Non-binary"
    case Other = "Other"
    case Pangender = "Pangender"
    case Trans = "Trans"
    case TransS = "Trans*"
    case TransFemale = "Trans Female"
    case TransSFemale = "Trans* Female"
    case TransMale = "Trans Male"
    case TransSMale = "Trans* Male"
    case TransMan = "Trans Man"
    case TransSMan = "Trans* Man"
    case TransPerson = "Trans Person"
    case TransSPerson = "Trans* Person"
    case TransWoman = "Trans Woman"
    case TransSWoman = "Trans* Woman"
    case Transfeminine = "Transfeminine"
    case Transgender = "Transgender"
    case TransgenderFemale = "Transgender Female"
    case TransgenderMale = "Transgender Male"
    case TransgenderPerson = "Transgender Person"
    case TransgenderWoman = "Transgender Woman"
    case Transmasculine = "Transmasculine"
    case Transsexual = "Transsexual"
    case TranssexualFemale = "Transsexual Female"
    case TranssexualMale = "Transsexual Male"
    case TranssexualMan = "Transsexual Man"
    case TranssexualPerson = "Transsexual Person"
    case TranssexualWoman = "Transsexual Woman"
    case TwoSpirit = "Two-Spirit"
}
