//
//  File.swift
//  
//
//  Created by Maxime De Greve on 22/07/2021.
//

import Vapor

enum Gender: String, Codable {
    case Agender = "agender"
    case Androgyne = "androgyne"
    case Androgynous = "androgynous"
    case Bigender = "bigender"
    case Cis = "cis"
    case Cisgender = "cisgender"
    case CisFemale = "cis_female"
    case CisMale = "cis_male"
    case CisMan = "cis_man"
    case CisWoman = "cis_woman"
    case CisgenderFemale = "cisgender_female"
    case CisgenderMale = "cisgender_male"
    case CisgenderMan = "cisgender_man"
    case CisgenderWoman = "cisgender_woman"
    case FemaletoMale = "female_to_male"
    case Female = "female"
    case FTM = "ftm"
    case GenderFluid = "gender_fluid"
    case GenderNonconforming = "gender_nonconforming"
    case GenderQuestioning = "gender_questioning"
    case GenderVariant = "gender_variant"
    case Genderqueer = "genderqueer"
    case Intersex = "intersex"
    case MaletoFemale = "male_to_female"
    case Male = "male"
    case MTF = "mtf"
    case Neither = "neither"
    case Neutrois = "neutrois"
    case NonBinary = "non-binary"
    case Other = "other"
    case Pangender = "pangender"
    case Trans = "trans"
    case TransS = "trans*"
    case TransFemale = "trans_female"
    case TransSFemale = "trans_female"
    case TransMale = "trans_male"
    case TransSMale = "trans*_male"
    case TransMan = "trans_man"
    case TransSMan = "trans*_man"
    case TransPerson = "trans_person"
    case TransSPerson = "trans*_person"
    case TransWoman = "trans_woman"
    case TransSWoman = "trans*_woman"
    case Transfeminine = "transfeminine"
    case Transgender = "transgender"
    case TransgenderFemale = "transgender_female"
    case TransgenderMale = "transgender_male"
    case TransgenderPerson = "transgender_person"
    case TransgenderWoman = "transgender_woman"
    case Transmasculine = "transmasculine"
    case Transsexual = "transsexual"
    case TranssexualFemale = "transsexual_female"
    case TranssexualMale = "transsexual_male"
    case TranssexualMan = "transsexual_man"
    case TranssexualPerson = "transsexual_person"
    case TranssexualWoman = "transsexual_woman"
    case TwoSpirit = "two-spirit"
}
