import Fluent

struct CreateGender: Migration {
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        database.enum("genders")
            .case("Agender")
            .case("Androgyne")
            .case("Androgynous")
            .case("Bigender")
            .case("Cis")
            .case("Cisgender")
            .case("Cis Female")
            .case("Cis Female")
            .case("Cis Male")
            .case("Cis Man")
            .case("Cis Woman")
            .case("Cisgender Female")
            .case("Cisgender Male")
            .case("Cisgender Man")
            .case("Cisgender Woman")
            .case("Female to Male")
            .case("Female")
            .case("FTM")
            .case("Gender Fluid")
            .case("Gender Nonconforming")
            .case("Gender Questioning")
            .case("Gender Variant")
            .case("Genderqueer")
            .case("Intersex")
            .case("Male to Female")
            .case("Male")
            .case("MTF")
            .case("Neither")
            .case("Neutrois")
            .case("Non-binary")
            .case("Other")
            .case("Pangender")
            .case("Trans")
            .case("Trans*")
            .case("Trans Female")
            .case("Trans* Female")
            .case("Trans Male")
            .case("Trans* Male")
            .case("Trans Man")
            .case("Trans* Man")
            .case("Trans Person")
            .case("Trans* Person")
            .case("Trans Woman")
            .case("Trans* Woman")
            .case("Transfeminine")
            .case("Transgender")
            .case("Transgender Female")
            .case("Transgender Male")
            .case("Transgender Person")
            .case("Transgender Woman")
            .case("Transmasculine")
            .case("Transsexual")
            .case("Transsexual Female")
            .case("Transsexual Male")
            .case("Transsexual Man")
            .case("Transsexual Person")
            .case("Transsexual Woman")
            .case("Two-Spirit")
            .create()
            .transform(to: database.eventLoop.makeSucceededVoidFuture())
    }

    func revert(on database: Database) -> EventLoopFuture<Void> {
        database.enum("genders").delete()
    }
}
